### ISSUE TITLE
Not able to run

### ISSUE THREAD

**Issue by joreilly02** [jsaddiction/Trailer-Technician#5]
Getting this error when running python3 TrailerTechnician.py -d "/Volumes/Seagate\ Movie\ Drive/Movies/Extremely\ Wicked\,\ Shockingly\ Evil\ and\ Vile\ \(2019\) " for example. Not sure what's happening.  Any idea? 

2020-09-12 07:15:29,516 - INFO - utils.updater - ****** Checking for Updates ******
Traceback (most recent call last):
  File "TrailerTechnician.py", line 6, in <module>
    from utils.arguments import get_arguments
  File "/Applications/Trailer-Technician/utils/arguments.py", line 2, in <module>
    from __init__ import NAME, VERSION, DESCRIPTION
  File "/Applications/Trailer-Technician/__init__.py", line 18, in <module>
    update = Update()
  File "/Applications/Trailer-Technician/utils/updater.py", line 41, in __init__
    self.updater = GitUpdateManager()
  File "/Applications/Trailer-Technician/utils/updater.py", line 95, in __init__
    self._git_path = self._find_working_git()
  File "/Applications/Trailer-Technician/utils/updater.py", line 122, in _find_working_git
    if config['updates']['git_path']:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'updates'

**Comment by jsaddiction** [comment]
Do you have an "updates" section in your settings.ini file?

**Comment by joreilly02** [comment]
I do not, am I supposed to?

**Comment by jsaddiction** [comment]
Let me upload a new settings example for you

**Comment by jsaddiction** [comment]
try that one

**Comment by joreilly02** [comment]
That worked.  You are a saint!   Thank you so much, appreciate it!
